name: "Sample GitHub Action in .NET 6"
description: "Finds matching files"
branding:
  icon: file
  color: blue
inputs:
  pattern:
    description: "File pattern."
    required: true
outputs:
  files:
    description: "Matching file paths."
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--pattern"
    - ${{ inputs.pattern }}
